window.day;
window.percentageScale;
window.profitScale;
window.cashToTrade;
window.bankCash;
window.salary;
window.salaryIncreaseCost;
window.stockReliability;
window.stockReliabilityCost;
window.transferType = "Deposit";
window.days = [];
window.portfolioValues = [];
window.portfolioChart;
window.portfolioStockValue;
window.totalMarketChart;
window.stocks = [];
window.stockNames = ['DAVE', 'GOOGL', 'GDM', 'VTS', 'OPPL', 'MFLX', 'META', 'NVDO', 'OAL', 'V'];
window.tracker = false;
window.stockUpperBound;
window.sharesAmount;
window.sharesBought;
window.previousStockValue;
window.marketTotalPrevious;
window.marketTotalNew;
window.totalPortfolioNew;
window.totalPortfolioPrevious;
window.firstTime;
window.calledBefore = false;
window.availableShares;